FROM public.ecr.aws/docker/library/node:lts-jod AS build

ARG BACKEND_BASE_URI=https://keeper.sparecores.net
ARG BACKEND_BASE_URI_SSR=https://keeper.sparecores.net
ENV BACKEND_BASE_URI=$BACKEND_BASE_URI
ENV BACKEND_BASE_URI_SSR=$BACKEND_BASE_URI_SSR

ARG POSTHOG_KEY
ARG POSTHOG_HOST
ENV POSTHOG_KEY=$POSTHOG_KEY
ENV POSTHOG_HOST=$POSTHOG_HOST

ARG SENTRY_ORG
ENV SENTRY_ORG=$SENTRY_ORG
ARG SENTRY_PROJECT
ENV SENTRY_PROJECT=$SENTRY_PROJECT
ARG SENTRY_URL
ENV SENTRY_URL=$SENTRY_URL

ARG SENTRY_DSN
ARG SENTRY_TRACE_SAMPLE_RATE=0
ARG SENTRY_PROFILE_SAMPLE_RATE=0
ARG SENTRY_ENVIRONMENT=development
ARG SENTRY_RELEASE
ENV SENTRY_DSN=$SENTRY_DSN
ENV SENTRY_TRACE_SAMPLE_RATE=$SENTRY_TRACE_SAMPLE_RATE
ENV SENTRY_PROFILE_SAMPLE_RATE=$SENTRY_PROFILE_SAMPLE_RATE
ENV SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT
ENV SENTRY_RELEASE=$SENTRY_RELEASE

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN --mount=type=secret,id=aws-key-id,env=AWS_ACCESS_KEY_ID npm run build:ssr:sc-www

FROM public.ecr.aws/docker/library/node:lts-jod

WORKDIR /usr/share/www
COPY package*.json ./
RUN npm install --omit=dev --no-audit
COPY --from=build /usr/src/app/dist/sc-www/server ./
COPY --from=build /usr/src/app/dist/sc-www/browser ./static

EXPOSE 3000
CMD ["node", "server.mjs"]
