import {
  LucideRefreshCcwDot,
  LucideBot,
  LucideBoxes,
  LucideEarthLock,
  LucideDatabaseZap,
  LucideImageUp,
  LucideArrowDownNarrowWide,
  LucideArrowDownWideNarrow,
  LucideBookText,
  LucideClipboard,
  LucideBox,
  LucideCheck,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideMail,
  LucideCpu,
  LucideDatabase,
  LucideDollarSign,
  LucideHouse,
  LucideHotel,
  LucideMemoryStick,
  LucidePcCase,
  LucideSearch,
  LucideServer,
  LucideSquareKanban,
  LucideUser,
  LucideBuilding2,
  LucideHeater,
  LucideChartCandlestick,
  LucideMapPinned,
  LucideScale,
  LucideEllipsis,
  LucideMenu,
  LucideLeaf,
  LucideShoppingCart,
  LucideChevronUp,
  LucideExternalLink,
  LucideInfo,
  LucideClipboardCheck,
  LucideScrollText,
  LucideTrash,
  LucideCircleX,
  LucideX,
  LucideCircleArrowDown,
  LucideCircleArrowUp,
  LucideArrowUpDown,
  LucideCopy,
  LucideHourglass,
  LucideGauge,
  LucideCalendarDays,
  LucideShipWheel,
  LucidePackageOpen,
  LucideLayers,
  LucideMicrochip,
  LucideQuote,
  LucideHandshake,
  LucideScanEye,
  LucideShieldCog,
  LucideSquareArrowUpRight,
  LucideBuilding,
  LucideRocket,
  LucideMessageSquareMore,
  LucideSquareArrowDown,
  LucideProjector,
  LucideNotebookText,
  LucideHeartHandshake,
  LucidePalette,
  LucideCircleCheck,
  LucideClock,
  LucideCircleAlert,
  LucideCircleCheckBig,
  LucideActivity,
  LucideLink,
  LucideFunnelX,
  LucideTriangleAlert,
  LucideCalendarSearch,
  LucideCreditCard,
  LucideColumns3Cog,
  LucideMessageCircleQuestionMark,
  LucideMaximize2,
  LucideMinus,
  LucidePlus,
  LucideDices,
  LucideTvMinimalPlay,
} from "@lucide/angular";
import type { LucideIconData } from "@lucide/angular";

const LucideCodesandbox = {
  name: "codesandbox",
  node: [
    [
      "path",
      {
        d: "M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z",
      },
    ],
    ["polyline", { points: "7.5 4.21 12 6.81 16.5 4.21" }],
    ["polyline", { points: "7.5 19.79 7.5 14.6 3 12" }],
    ["polyline", { points: "21 12 16.5 14.6 16.5 19.79" }],
    ["polyline", { points: "3.27 6.96 12 12.01 20.73 6.96" }],
    ["line", { x1: "12", x2: "12", y1: "22.08", y2: "12" }],
  ],
} satisfies LucideIconData;

const LucideFacebook = {
  name: "facebook",
  node: [
    [
      "path",
      {
        d: "M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z",
      },
    ],
  ],
} satisfies LucideIconData;

const LucideGithub = {
  name: "github",
  node: [
    [
      "path",
      {
        d: "M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.4 5.4 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4",
      },
    ],
    ["path", { d: "M9 18c-4.51 2-5-2-7-2" }],
  ],
} satisfies LucideIconData;

const LucideLinkedin = {
  name: "linkedin",
  node: [
    [
      "path",
      { d: "M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-4 0v7h-4v-7a6 6 0 0 1 6-6z" },
    ],
    ["rect", { width: "4", height: "12", x: "2", y: "9" }],
    ["circle", { cx: "4", cy: "4", r: "2" }],
  ],
} satisfies LucideIconData;

const LucideTwitter = {
  name: "twitter",
  node: [
    [
      "path",
      {
        d: "M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z",
      },
    ],
  ],
} satisfies LucideIconData;

const LucideYoutube = {
  name: "youtube",
  node: [
    [
      "path",
      {
        d: "M2.5 17a24.1 24.1 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.6 49.6 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.1 24.1 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.6 49.6 0 0 1-16.2 0A2 2 0 0 1 2.5 17",
      },
    ],
    ["path", { d: "m10 15 5-3-5-3z" }],
  ],
} satisfies LucideIconData;

export const lucideIcons = [
  LucideRefreshCcwDot,
  LucideBot,
  LucideBoxes,
  LucideEarthLock,
  LucideDatabaseZap,
  LucideImageUp,
  LucideArrowDownNarrowWide,
  LucideArrowDownWideNarrow,
  LucideBookText,
  LucideClipboard,
  LucideBox,
  LucideCheck,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideMail,
  LucideCodesandbox,
  LucideCpu,
  LucideDatabase,
  LucideDollarSign,
  LucideFacebook,
  LucideGithub,
  LucideHouse,
  LucideHotel,
  LucideLinkedin,
  LucideMemoryStick,
  LucidePcCase,
  LucideSearch,
  LucideServer,
  LucideSquareKanban,
  LucideTwitter,
  LucideUser,
  LucideBuilding2,
  LucideHeater,
  LucideChartCandlestick,
  LucideMapPinned,
  LucideScale,
  LucideEllipsis,
  LucideMenu,
  LucideLeaf,
  LucideShoppingCart,
  LucideChevronUp,
  LucideExternalLink,
  LucideInfo,
  LucideClipboardCheck,
  LucideScrollText,
  LucideYoutube,
  LucideTrash,
  LucideCircleX,
  LucideX,
  LucideCircleArrowDown,
  LucideCircleArrowUp,
  LucideArrowUpDown,
  LucideCopy,
  LucideHourglass,
  LucideGauge,
  LucideCalendarDays,
  LucideShipWheel,
  LucidePackageOpen,
  LucideLayers,
  LucideMicrochip,
  LucideQuote,
  LucideHandshake,
  LucideScanEye,
  LucideShieldCog,
  LucideSquareArrowUpRight,
  LucideBuilding,
  LucideRocket,
  LucideMessageSquareMore,
  LucideSquareArrowDown,
  LucideProjector,
  LucideNotebookText,
  LucideHeartHandshake,
  LucidePalette,
  LucideCircleCheck,
  LucideClock,
  LucideCircleAlert,
  LucideCircleCheckBig,
  LucideActivity,
  LucideLink,
  LucideFunnelX,
  LucideTriangleAlert,
  LucideCalendarSearch,
  LucideCreditCard,
  LucideColumns3Cog,
  LucideMessageCircleQuestionMark,
  LucideMaximize2,
  LucideMinus,
  LucidePlus,
  LucideDices,
  LucideTvMinimalPlay,
] as const;
