name: Tests
on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install --include=dev
      - name: Run ESLint
        run: npm run lint
      - name: Run Prettier check
        run: npm run prettier:check

  unit-tests:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install --include=dev
      - name: Set up Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
      - name: Run Jasmine Karma tests
        run: npm run test:ci
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
          NG_APP_BACKEND_BASE_URI: https://keeper.sparecores.net
          NG_APP_BACKEND_BASE_URI_SSR: https://keeper.sparecores.net
          NG_APP_SENTRY_DSN: ""
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-coverage
          path: coverage
          retention-days: 7
          if-no-files-found: ignore

  cypress-run:
    needs: unit-tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Inject legal docs
        env:
          LEGAL_TOKEN: ${{ secrets.LEGAL_TOKEN }}
          LEGAL_URL: ${{ secrets.LEGAL_URL }}
        run: 'curl -s -L -H "Authorization: token ${LEGAL_TOKEN}" ${LEGAL_URL} | tar xz --strip-components=1'
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run prebuild
          start: npm start
          wait-on: "http://localhost:4200"
          browser: chrome
        env:
          CYPRESS_BASE_URL: http://localhost:4200
          NG_APP_BACKEND_BASE_URI: https://keeper.sparecores.net
          NG_APP_BACKEND_BASE_URI_SSR: https://keeper.sparecores.net
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: |
            cypress/screenshots
            cypress-image-diff-screenshots
            cypress-image-diff-html-report
          retention-days: 7
          if-no-files-found: ignore
